# Generated by Django 2.0.13 on 2019-03-30 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeworkapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='homework',
            table='homeworks',
        ),
    ]
