# Generated by Django 2.0.6 on 2019-03-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworkapp', '0003_auto_20190306_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='is_release',
            field=models.BooleanField(default=False, verbose_name='是否发布'),
        ),
    ]
