# Generated by Django 2.0.6 on 2019-03-06 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeworkapp', '0004_homework_is_release'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='note',
        ),
    ]
