# Generated by Django 2.0.6 on 2019-03-05 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=100, verbose_name='课程标题')),
                ('course_cover', models.ImageField(max_length=200, upload_to='resources/cover/%Y%m%d', verbose_name='课程封面')),
                ('course_describe', models.CharField(blank=True, max_length=300, verbose_name='课程描述')),
                ('course_click_nums', models.IntegerField(default=0, editable=False, verbose_name='点击量')),
                ('course_add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.TeacherProfile', verbose_name='教师')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'db_table': 'course',
                'ordering': ['course_click_nums'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=100, verbose_name='视频标题')),
                ('video_add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('video_upload', models.FileField(max_length=200, upload_to='resources/video/%Y%m%d', verbose_name='视频')),
                ('video_time', models.CharField(default=0, editable=False, max_length=30, verbose_name='视频时长')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoapp.Course', verbose_name='课程')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
                'db_table': 'video',
            },
        ),
    ]
