# Generated by Django 2.0.13 on 2019-03-30 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='courses',
        ),
        migrations.AlterModelTable(
            name='video',
            table='videos',
        ),
    ]
