# Generated by Django 2.0.13 on 2019-03-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cover',
            field=models.ImageField(max_length=200, upload_to='cover/%Y%m%d', verbose_name='课程封面'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(max_length=200, upload_to='video/%Y%m%d', verbose_name='视频'),
        ),
    ]
