# Generated by Django 2.0.6 on 2019-03-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('number', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='学号')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('password', models.CharField(max_length=200, verbose_name='密码')),
                ('identity', models.CharField(default='student', editable=False, max_length=20, verbose_name='身份')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('total_time', models.CharField(default=0, editable=False, max_length=20, verbose_name='观看视频总时长')),
                ('profile_photo', models.ImageField(default='images/user_profile/default_student.png', editable=False, upload_to='images/user_profile/')),
            ],
            options={
                'verbose_name': '学生表',
                'verbose_name_plural': '学生表',
                'db_table': 'student_profile',
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('number', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='学号')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('password', models.CharField(max_length=200, verbose_name='密码')),
                ('identity', models.CharField(default='teacher', editable=False, max_length=20, verbose_name='身份')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('profile_photo', models.ImageField(default='images/user_profile/default_teacher.png', editable=False, upload_to='images/user_profile/')),
            ],
            options={
                'verbose_name': '教师表',
                'verbose_name_plural': '教师表',
                'db_table': 'teacher_profile',
            },
        ),
    ]
