# Generated by Django 2.0.13 on 2019-03-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_photo',
            field=models.ImageField(default='images/user_profile/default/default_student.png', editable=False, upload_to='images/user_profile/'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='profile_photo',
            field=models.ImageField(default='images/user_profile/default/default_teacher.png', editable=False, upload_to='images/user_profile/'),
        ),
    ]
