# Generated by Django 2.0.13 on 2019-03-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursewareapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseware',
            name='file',
            field=models.FileField(max_length=200, upload_to='courseware/%Y%m%d', verbose_name='课件路径'),
        ),
    ]
